# NumPy
## Operations

In [2]:
import numpy as np

The key to making computation on NumPy arrays fast is to use vectorized operations, generally implemented through NumPy universal functions (ufuncs). 
Vectorized operation performing an operation on the array are applied to each element (one by one).

Computations using vectorization through ufuncs are nearly always more efficient than their counterpart implemented through Python loops, especially as the arrays grow in size. Any time you see such a loop in a Python script, you should consider whether it can be replaced with a vectorized expression.

In [14]:
x = np.array([np.arange(1, 6),np.arange(2, 7)])
print(x)

[[1 2 3 4 5]
 [2 3 4 5 6]]


**Reduce**  
Repeatedly applies a given operation to the elements of an array until only a single result remains for a 1d or 
a result per column (axis=1) or a result per row (axis=0)

**Add reduce**  
Calling reduce on the add ufunc returns the sum of all elements in the array  

In [17]:
np.add.reduce(x, axis=1)

array([15, 20])

**Multiply all values**

In [20]:
np.multiply.reduce(np.multiply.reduce(x))

86400

**Store all intermediate values**   
similar to a running sum, use Accumulate

In [27]:
y=np.arange(6)
np.add.accumulate(y)

array([ 0,  1,  3,  6, 10, 15])

Whenever possible, make sure that you are using the NumPy version of aggregates when operating on NumPy arrays 

**Max / Min**

In [29]:
np.max(y) 
np.min(y) 
np.sum(y)

15

**Minimum value within each column**  
specify axis=0:

In [30]:
np.min(x, axis=0)

array([1, 2, 3, 4, 5])

**Maximum value within each row**  
specify axis=1:

In [31]:
np.min(x, axis=1)

array([1, 2])

**NaN-safe Aggregations**  
most aggregates have a NaN-safe counterpart that computes the result while ignoring missing values

np.sum  / np.nansum  
np.prod / np.nanprod

**BOOLEAN Arrays**

**Count True values**

In [32]:
 # how many values less than 6?
np.count_nonzero(x < 6)

9

In [33]:
# False is interpreted as 0, and True is inter‐ preted as 1:

In [34]:
np.sum(x < 6)

9

In [35]:
# how many values less than 6 in each row? 

In [36]:
np.sum(x < 6, axis=1)

array([5, 4])

In [37]:
#Any values greater than 8? 

In [39]:
np.any(x > 8)

False

In [40]:
# are all values less than 10? 

In [41]:
np.all(x < 10)

True

In [42]:
# are all values in each row less than 8? 

In [43]:
np.all(x < 8, axis=1)

array([ True,  True])

In [44]:
# count values between an interval

In [45]:
np.sum((x > 0.5) & (x < 1))

0

**Masking operations**  
select values from an array based on a condition

In [49]:
# extract values from x where x < 5
print(x)
x[x < 5]

[[1 2 3 4 5]
 [2 3 4 5 6]]


array([1, 2, 3, 4, 2, 3, 4])

**Define a mask to be reused**

In [56]:
mask = (x < 5)
x[mask]

array([1, 2, 3, 4, 2, 3, 4])

In [57]:

np.median(x[mask])


3.0