# NumPy
## Array Attributes

In [2]:
import numpy as np
x3 = np.random.randint(10, size=(3, 4, 5))
print(x3)

[[[9 2 5 0 9]
  [7 6 5 6 5]
  [8 8 0 3 4]
  [7 1 8 5 1]]

 [[8 6 7 3 9]
  [4 6 4 8 0]
  [4 5 4 8 4]
  [0 9 6 3 2]]

 [[2 6 4 9 0]
  [9 2 3 4 1]
  [7 9 4 3 5]
  [7 8 5 3 8]]]


**Number of Dimensions (3)**  
array.ndim

In [3]:
print("x3 ndim: ", x3.ndim) 

x3 ndim:  3


**Dimensions size (3, 4, 5)**  
array.shape

In [4]:
print("x3 shape:", x3.shape)

x3 shape: (3, 4, 5)


**Array size ( 3 x 4 x 5 = 60)**  
array.size

In [12]:
print("x3 size: ", x3.size)

x3 size:  60


**Array data type**  
array.dtype

In [6]:
print("dtype:", x3.dtype)

dtype: int64


**Array max / min**  
Values - np.max() / np.min()  
Indexes - np.argmax() / np.argmin()

In [11]:
print("Max: {} at index {}".format(np.max(x3), np.argmax(x3)))
print("Min: {} at index {}".format(np.min(x3), np.argmin(x3)))

Max: 9 at index 0
Min: 0 at index 3
